version: '3'

volumes:
  local_postgres_data: { }

services:
  test_ci:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_local
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - .:/work
    environment:
      - POSTGRES_DSN=postgres://test_ci:test_ci@postgres:5432/test_ci
      - POSTGRES_DSN_TEST=postgres://test_ci:test_ci@postgres:5432/test_ci_{}
    ports:
      - 8000:8000
    command:
      - /scripts/start-production.sh

  postgres:
    image: postgres:13-alpine
    ports:
      - 15432:5432
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test_ci
      - POSTGRES_PASSWORD=test_ci
      - POSTGRES_DB=test_ci
